server:
   port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
   nacos:
    discovery:
      #ngnix的1111端口,做集群
      server-addr: 192.168.153.131:1111



management:
  endpoints:
    web:
      exposure:
        include: '*'
