server:
  port: 9527

spring:
   application:
     name: cloud-gateway
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
     url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8 # 数据库名称
     username: root
     password: qq1223

   cloud:
     gateway:
        discovery:
          locator:
            enabled: true #开启注册中心动态创建路由的功能,利用微服务名进行路由
        routes:
          - id: payment_routh             # 路由的id,没有固定规则,但要求唯一,建议配合服务名
             #uri: http://localhost:8001     # 匹配后提供服务的路由地址
            uri: lb://cloud-payment-service
            predicates:
               - Path=/payment/get/**       # 断言,路径相匹配的进行路由


          - id: payment_routh2             # 路由的id,没有固定规则,但要求唯一,建议配合服务名
             #uri: http://localhost:8001     # 匹配后提供服务的路由地址
            uri: lb://cloud-payment-service
            predicates:
               - Path=/payment/lb/**       # 断言,路径相匹配的进行路由
               #- After=2020-04-21T15:29:05.355+08:00[Asia/Shanghai] #什么时间后才能用
              # - Before=2020-04-21T15:29:05.355+08:00[Asia/Shanghai]
              # - Between=2020-04-21T15:29:05.355+08:00[Asia/Shanghai],2020-04-21T18:29:05.355+08:00[Asia/Shanghai]
              # - Cookis=username,csc
              # - Header=X-Request-Id,\d+
              # - Host=**.baidu.com
              # - Method=GET
              # - Query=username,\d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      #defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka #集群
      defaultZone: http://eureka7001.com:7001/eureka  #单机


