server:
  port: 80

eureka:
    client:
      #false表示不向注册中心注册自己
      register-with-eureka: false
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/ #单机
         #defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka  #集群
    instance:
      prefer-ip-address: true

feign:
    hystrix:
       enabled: true
